export const TEST_IDS = {
  ADDITIONAL_INFO_CONTAINER: 'ADDITIONAL_INFO_CONTAINER',
  ADDITIONAL_INFO_BUTTON: 'ADDITIONAL_INFO_BUTTON',
  ADDITIONAL_INFO_ICON: 'ADDITIONAL_INFO_ICON',
  TIMER_TEXT: 'TIMER_TEXT',
  TIMER_BUTTON_IMAGE: 'TIMER_BUTTON_IMAGE',
};
