export const TEST_IDS = {
  ADDITIONAL_INFO_CONTAINER: 'ADDITIONAL_INFO_CONTAINER',
  ADDITIONAL_INFO_BUTTON: 'ADDITIONAL_INFO_BUTTON',
  ADDITIONAL_INFO_ICON: 'ADDITIONAL_INFO_ICON',
  TIMER_TEXT: 'TIMER_TEXT',
  TIMER_BUTTON_IMAGE: 'TIMER_BUTTON_IMAGE',
  TASK_LIST_DAY_CONTAINER: 'TASK_LIST_DAY_CONTAINER',
  TASK_LIST_TASK_TIME_CONTAINER: 'TASK_LIST_TASK_TIME_CONTAINER',
  TASK_ENTRIES_CONTAINER: 'TASK_ENTRIES_CONTAINER',
  REPLAY_BUTTON: 'REPLAY_BUTTON',
};
